# version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: User_Management
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
